include: package:lints/recommended.yaml

analyzer:
  exclude:
    - .dart_tool/**

linter:
  rules:
    # Consistency
    - always_declare_return_types
    - annotate_overrides
    - avoid_relative_lib_imports
    - avoid_renaming_method_parameters
    - curly_braces_in_flow_control_structures
    - empty_statements
    - prefer_const_constructors
    - prefer_final_fields
    - prefer_final_locals

    # Documentation
    - always_put_required_named_parameters_first
    - provide_deprecation_message
    - public_member_api_docs

    # Safety
    - avoid_print
    - avoid_types_as_parameter_names
    - no_duplicate_case_values
    - unnecessary_null_checks