name: flutter_architect_cli
description: A CLI tool to scaffold Flutter projects with multiple architecture patterns (clean architecture is architecture pattern)
version: 1.0.1
repository: https://github.com/Nader15/flutter_architect_cli.git
homepage: https://github.com/Nader15/flutter_architect_cli.git

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  path: ^1.8.3

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0

executables:
  flutter_architect: